name: CICD

on:
 workflow_dispatch:
   inputs:
     environment:
       description: this is the environment value where this workflow runs
       default: 'dev'
       required: true
       type: choice   
       options:
         - dev
         - prod
         - staging


jobs:
  code: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "code is checking"

  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: build Docker image
        run: echo "docker image building completed"

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: test the container
        run: echo "testing the container"

  deploy:
    needs: [test]
    runs-on: ubuntu-22.04
    steps:
      - name: deploying the app
        run: echo " deploying with docker-compose"
        
