name: Hello

on:
  push:
    branches: workflow_dispatch
jobs:

  greet:
    runs-on: ubuntu-latest

    steps:
      - name: say hello to users
        run: echo "hello kanha"

      - name: say hello to others
        run: echo "hello $USER"
        
  details:
     runs-on: ubuntu-latest
     steps:
       - name: i have create second workflow
         run: echo " you created your second workflow"
       
