name: Hello

on:
  push:
    branches: [main]

jobs:

  greet:
    runs-on: ubuntu-latest

    steps:
      - name: say hello to users
        run: echo "hello kanha"

      - name: say hello to others
        run: echo "hello $USER"
       
